#!/bin/bash

# setup SSHReverseTunnel
# vim: ts=3 sts=3 sw=3 et nu list

#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources

if [ $scriptAction == 'NONE' ]; then
   scriptAction='INSTALL'
fi

if [ $scriptAction == 'INSTALL' ]; then
   if [[ ! -f ~root/.ssh/id_ed25519 ]]; then
      logMessage "Creating SSH Key for SSH Reverse Tunnel."
      ssh-keygen -t ed25519 -C "venus $(dbus -y com.victronenergy.system /Serial GetValue | tr -d \')" -q -N '' -f ~root/.ssh/id_ed25519
   else
      logMessage "SSH Key for SSH Reverse Tunnel already exists."
   fi

   logMessage "SSH Reverse Tunnel Publickey: $(cat ~root/.ssh/id_ed25519.pub)"

   if [[ ! -d /var/log/SSHReverseTunnel ]]; then
      mkdir /var/log/SSHReverseTunnel
   fi

   installService SSHReverseTunnel
fi

if [ $scriptAction == 'UNINSTALL' ]; then
   removeService SSHReverseTunnel
fi

endScript
